/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-28 03:57:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.xava.editors;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import java.util.Collection;
import java.util.Map;
import org.openxava.util.Maps;
import org.openxava.util.Is;
import org.openxava.util.XavaPreferences;
import org.openxava.view.View;
import org.openxava.model.meta.MetaProperty;
import org.openxava.model.meta.MetaReference;
import org.openxava.web.WebEditors;
import org.openxava.controller.meta.MetaController;
import org.openxava.controller.meta.MetaAction;
import org.openxava.web.Ids;
import org.openxava.controller.meta.MetaControllers;
import org.openxava.util.Is;
import org.openxava.util.XavaPreferences;
import org.openxava.controller.meta.MetaAction;
import org.openxava.web.Ids;
import org.openxava.controller.meta.MetaControllers;
import org.openxava.util.Is;
import org.openxava.util.XavaPreferences;

public final class collectionEditor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/xava/editors/../collectionList.jsp", Long.valueOf(1714783506000L));
    _jspx_dependants.put("jar:file:/C:/Users/DELL/Desktop/Clases/POO/jaguarcare-openxava/target/jaguarcare/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt-1_0.tld", Long.valueOf(1153406682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1153506114000L));
    _jspx_dependants.put("/xava/editors/../imports.jsp", Long.valueOf(1714783508000L));
    _jspx_dependants.put("/WEB-INF/openxava.tld", Long.valueOf(1714783506000L));
    _jspx_dependants.put("/xava/editors/../collectionFromModel.jsp", Long.valueOf(1714783506000L));
    _jspx_dependants.put("jar:file:/C:/Users/DELL/Desktop/Clases/POO/jaguarcare-openxava/target/jaguarcare/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0.tld", Long.valueOf(1153406682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(14);
    _jspx_imports_classes.add("org.openxava.model.meta.MetaProperty");
    _jspx_imports_classes.add("org.openxava.controller.meta.MetaController");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("org.openxava.util.XavaPreferences");
    _jspx_imports_classes.add("org.openxava.model.meta.MetaReference");
    _jspx_imports_classes.add("java.util.Collection");
    _jspx_imports_classes.add("org.openxava.web.Ids");
    _jspx_imports_classes.add("org.openxava.util.Is");
    _jspx_imports_classes.add("org.openxava.controller.meta.MetaAction");
    _jspx_imports_classes.add("org.openxava.util.Maps");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("org.openxava.view.View");
    _jspx_imports_classes.add("org.openxava.web.WebEditors");
    _jspx_imports_classes.add("org.openxava.controller.meta.MetaControllers");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005flink_0026_005fargv_005faction;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fxava_005flink_0026_005fargv_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fxava_005flink_0026_005fargv_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      org.openxava.controller.ModuleContext context = null;
      synchronized (session) {
        context = (org.openxava.controller.ModuleContext) _jspx_page_context.getAttribute("context", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (context == null){
          context = new org.openxava.controller.ModuleContext();
          _jspx_page_context.setAttribute("context", context, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
      org.openxava.util.Messages errors = null;
      errors = (org.openxava.util.Messages) _jspx_page_context.getAttribute("errors", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (errors == null){
        errors = new org.openxava.util.Messages();
        _jspx_page_context.setAttribute("errors", errors, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      org.openxava.web.style.Style style = null;
      style = (org.openxava.web.style.Style) _jspx_page_context.getAttribute("style", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (style == null){
        style = new org.openxava.web.style.Style();
        _jspx_page_context.setAttribute("style", style, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

String collectionName = request.getParameter("collectionName");
String viewObject = request.getParameter("viewObject");
String listEditor = request.getParameter("listEditor");  
View view = (View) context.get(request, viewObject);
View collectionView = view.getSubview(collectionName);
if (!Is.emptyString(listEditor)) {
	collectionView.setDefaultListActionsForCollectionsIncluded(false);
	collectionView.setDefaultRowActionsForCollectionsIncluded(false); 
}
View subview = view.getSubview(collectionName);
MetaReference ref = view.getMetaModel().getMetaCollection(collectionName).getMetaReference();
String viewName = viewObject + "_" + collectionName;
String propertyPrefixAccumulated = request.getParameter("propertyPrefix");
String idCollection = org.openxava.web.Collections.id(request, collectionName); 
boolean collectionEditable = subview.isCollectionEditable();
boolean collectionMembersEditables = subview.isCollectionMembersEditables();
boolean hasListActions = subview.hasListActions();
String lineAction = ""; 
if (collectionEditable || collectionMembersEditables) {
	lineAction = subview.getEditCollectionElementAction();
}
else {
	lineAction = subview.getViewCollectionElementAction();
}
String propertyPrefix = propertyPrefixAccumulated == null?collectionName + ".":propertyPrefixAccumulated + collectionName + "."; 

      out.write("\n");
      out.write("<table width=\"100%\" ");
      out.print(style.getListCellSpacing());
      out.write('>');
      out.write('\n');
 if (XavaPreferences.getInstance().isDetailOnBottomInCollections()) { 
      out.write("\n");
      out.write("<tr><td>\n");
 try { 
      out.write('\n');
      out.write('	');
 if (!Is.emptyString(listEditor)) { 
      out.write('\n');
      out.write('	');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, listEditor + ((listEditor).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("rowAction", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(lineAction), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("viewObject", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(viewName), request.getCharacterEncoding()), out, false);
      out.write('\n');
      out.write('	');

		} else if (collectionView.isCollectionFromModel()) {
	
      out.write('\n');
      out.write('	');
      out.write('	');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

String tabObject = request.getParameter("tabObject"); 
tabObject = (tabObject == null || tabObject.equals(""))?"xava_tab":tabObject;
String onSelectCollectionElementAction = subview.getOnSelectCollectionElementAction();
MetaAction onSelectCollectionElementMetaAction = Is.empty(onSelectCollectionElementAction) ? null : MetaControllers.getMetaAction(onSelectCollectionElementAction);
boolean resizeColumns = style.allowsResizeColumns() && XavaPreferences.getInstance().isResizeColumns();
boolean sortable = subview.isCollectionSortable();

      out.write('\n');
 if (resizeColumns) { 
      out.write(" \n");
      out.write("<div class=\"");
      if (_jspx_meth_xava_005fid_005f0(_jspx_page_context))
        return;
      out.write(" ox-overflow-auto\">\n");
 } 
      out.write("\n");
      out.write("<table id=\"");
      //  xava:id
      org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f1 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
      boolean _jspx_th_xava_005fid_005f1_reused = false;
      try {
        _jspx_th_xava_005fid_005f1.setPageContext(_jspx_page_context);
        _jspx_th_xava_005fid_005f1.setParent(null);
        // /xava/editors/../collectionFromModel.jsp(20,11) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005fid_005f1.setName(idCollection);
        int _jspx_eval_xava_005fid_005f1 = _jspx_th_xava_005fid_005f1.doStartTag();
        if (_jspx_th_xava_005fid_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f1);
        _jspx_th_xava_005fid_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f1, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f1_reused);
      }
      out.write("\" class=\"ox-list\" ");
      out.print(style.getListCellSpacing());
      out.write('>');
      out.write('\n');
 if (sortable) { 
      out.write("<tbody class=\"xava_sortable_row\">");
 } 
      out.write(" \n");
      out.write("<tr class=\"ox-list-header\">\n");
      out.write("	");

		if (lineAction != null) {
	
      out.write("	\n");
      out.write("	<th class=\"ox-list-header\"></th>\n");
      out.write("	");

		}
	
      out.write("	\n");
      out.write("	<th class=\"ox-list-header\" width=\"5\">\n");
      out.write("	");

	
      out.write("\n");
      out.write("	<input type=\"checkbox\" name=\"");
      if (_jspx_meth_xava_005fid_005f2(_jspx_page_context))
        return;
      out.write("\" value=\"");
      out.print(propertyPrefix);
      out.write("selected_all\" \n");
      out.write("		data-on-select-collection-element-action=\"");
      out.print(onSelectCollectionElementAction);
      out.write("\"\n");
      out.write("		data-view-object=\"");
      out.print(idCollection);
      out.write("\"\n");
      out.write("		data-prefix=\"");
      out.print(propertyPrefix);
      out.write("\"\n");
      out.write("		data-tab-object=\"");
      out.print(tabObject);
      out.write("\"/>\n");
      out.write("	</th>\n");

	// Heading
Iterator it = subview.getMetaPropertiesList().iterator();
for (int columnIndex=0; it.hasNext(); columnIndex++) {
	MetaProperty p = (MetaProperty) it.next();
	String label = p.getQualifiedLabel(request);
	int columnWidth = subview.getCollectionColumnWidth(columnIndex);
	String width = columnWidth<0 || !resizeColumns?"":"data-width=" + columnWidth;

      out.write("\n");
      out.write("	<th class=\"ox-list-header ox-padding-right-0\">\n");
      out.write("		<div id=\"");
      //  xava:id
      org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f3 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
      boolean _jspx_th_xava_005fid_005f3_reused = false;
      try {
        _jspx_th_xava_005fid_005f3.setPageContext(_jspx_page_context);
        _jspx_th_xava_005fid_005f3.setParent(null);
        // /xava/editors/../collectionFromModel.jsp(49,11) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005fid_005f3.setName(idCollection);
        int _jspx_eval_xava_005fid_005f3 = _jspx_th_xava_005fid_005f3.doStartTag();
        if (_jspx_th_xava_005fid_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f3);
        _jspx_th_xava_005fid_005f3_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f3, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f3_reused);
      }
      out.write("_col");
      out.print(columnIndex);
      out.write("\" class=\"");
      out.print(((resizeColumns)?("xava_resizable"):("")));
      out.write('"');
      out.write(' ');
      out.print(width);
      out.write(">\n");
      out.write("		");
if (resizeColumns) {
      out.write("<nobr>");
}
      out.write('\n');
      out.write('	');
      out.write('	');
      out.print(label);
      out.write("&nbsp;\n");
      out.write("		");
if (resizeColumns) {
      out.write("</nobr>");
}
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</th>\n");

	}

      out.write("\n");
      out.write("</tr>\n");
      out.write("\n");

	// Values
Collection aggregates = subview.getCollectionValues();
View parent = view.getParent();
boolean parentHasSections = parent != null && parent.hasSections();
boolean condition = (view.isKeyEditable() && parentHasSections && !view.isRepresentsEntityReference()); 
if (aggregates == null || condition) aggregates = java.util.Collections.EMPTY_LIST;
Iterator itAggregates = aggregates.iterator();
for (int f=0; itAggregates.hasNext(); f++) {
	Map row = (Map) itAggregates.next();
	String cssClass=f%2==0?"ox-list-pair":"ox-list-odd";
	String cssCellClass=f%2==0?"ox-list-pair":"ox-list-odd";
	String selectedClass = "";
	if (f == subview.getCollectionEditingRow()) { 
		selectedClass = f%2==0?style.getListPairSelected():style.getListOddSelected();
		cssClass = cssClass + " " + selectedClass;		
		if (style.isApplySelectedStyleToCellInList()) cssCellClass = cssCellClass + " " + selectedClass; 
	}		
	String idRow = Ids.decorate(request, propertyPrefix) + f;	
	String events=f%2==0?style.getListPairEvents():style.getListOddEvents(); 

      out.write("\n");
      out.write("<tr id=\"");
      out.print(idRow);
      out.write("\" class=\"");
      out.print(cssClass);
      out.write('"');
      out.write(' ');
      out.print(events);
      out.write('>');
      out.write('\n');

	if (lineAction != null) {

      out.write("\n");
      out.write("<td class=\"");
      out.print(cssCellClass);
      out.write(" ox-list-action-cell\">\n");
      out.write("<nobr>\n");
      out.write("	");
	if (sortable) { 
      out.write("\n");
      out.write("	<i class=\"xava_handle mdi mdi-swap-vertical\"></i>	\n");
      out.write("	");
  } 
      out.write('	');
      out.write('\n');
      //  xava:action
      org.openxava.web.taglib.ActionTag _jspx_th_xava_005faction_005f0 = (org.openxava.web.taglib.ActionTag) _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.get(org.openxava.web.taglib.ActionTag.class);
      boolean _jspx_th_xava_005faction_005f0_reused = false;
      try {
        _jspx_th_xava_005faction_005f0.setPageContext(_jspx_page_context);
        _jspx_th_xava_005faction_005f0.setParent(null);
        // /xava/editors/../collectionFromModel.jsp(90,0) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005faction_005f0.setAction(lineAction);
        // /xava/editors/../collectionFromModel.jsp(90,0) name = argv type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005faction_005f0.setArgv("row="+f + ",viewObject="+viewName);
        int _jspx_eval_xava_005faction_005f0 = _jspx_th_xava_005faction_005f0.doStartTag();
        if (_jspx_th_xava_005faction_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.reuse(_jspx_th_xava_005faction_005f0);
        _jspx_th_xava_005faction_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005faction_005f0, _jsp_getInstanceManager(), _jspx_th_xava_005faction_005f0_reused);
      }
      out.write('\n');
 
		if (style.isSeveralActionsPerRow())
			for (java.util.Iterator itRowActions = subview.getRowActionsNames().iterator(); itRowActions.hasNext(); ) { 	
				String rowAction = (String) itRowActions.next();		

      out.write('\n');
      //  xava:action
      org.openxava.web.taglib.ActionTag _jspx_th_xava_005faction_005f1 = (org.openxava.web.taglib.ActionTag) _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.get(org.openxava.web.taglib.ActionTag.class);
      boolean _jspx_th_xava_005faction_005f1_reused = false;
      try {
        _jspx_th_xava_005faction_005f1.setPageContext(_jspx_page_context);
        _jspx_th_xava_005faction_005f1.setParent(null);
        // /xava/editors/../collectionFromModel.jsp(96,0) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005faction_005f1.setAction(rowAction);
        // /xava/editors/../collectionFromModel.jsp(96,0) name = argv type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005faction_005f1.setArgv("row=" + f + ",viewObject="+viewName);
        int _jspx_eval_xava_005faction_005f1 = _jspx_th_xava_005faction_005f1.doStartTag();
        if (_jspx_th_xava_005faction_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.reuse(_jspx_th_xava_005faction_005f1);
        _jspx_th_xava_005faction_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005faction_005f1, _jsp_getInstanceManager(), _jspx_th_xava_005faction_005f1_reused);
      }
      out.write('\n');

		}

      out.write("\n");
      out.write("</nobr>\n");
      out.write("</td>\n");

	} 

      out.write("\n");
      out.write("<td class=\"");
      out.print(cssCellClass);
      out.write("\" width=\"5\">\n");
      out.write("<input class=\"xava_selected\" type=\"checkbox\" name=\"");
      if (_jspx_meth_xava_005fid_005f4(_jspx_page_context))
        return;
      out.write("\" value=\"");
      out.print(propertyPrefix);
      out.write("__SELECTED__:");
      out.print(f);
      out.write("\" \n");
      out.write("	data-on-select-collection-element-action=\"");
      out.print(onSelectCollectionElementAction);
      out.write("\"\n");
      out.write("	data-row-id=\"");
      out.print(idRow);
      out.write("\"\n");
      out.write("	data-row=\"");
      out.print(f);
      out.write("\"\n");
      out.write("	data-view-object=\"");
      out.print(viewName);
      out.write("\"\n");
      out.write("	data-tab-object=\"");
      out.print(tabObject);
      out.write("\"\n");
      out.write("	data-confirm-message=\"");
      out.print(Is.empty(onSelectCollectionElementMetaAction)?"":onSelectCollectionElementMetaAction.getConfirmMessage());
      out.write("\"\n");
      out.write("	data-takes-long=\"");
      out.print(Is.empty(onSelectCollectionElementMetaAction)?false:onSelectCollectionElementMetaAction.isTakesLong());
      out.write("\"\n");
      out.write("/>\n");
      out.write("</td>\n");

	it = subview.getMetaPropertiesList().iterator();	
	for (int columnIndex = 0; it.hasNext(); columnIndex++) { 
		MetaProperty p = (MetaProperty) it.next();
		String align =p.isNumber() && !p.hasValidValues()?"ox-text-align-right":"";
		int columnWidth = subview.getCollectionColumnWidth(columnIndex);
		String width = columnWidth<0 || !resizeColumns?"":"data-width=" + columnWidth; 
		String fvalue = null;
		Object value = null;
		String propertyName = p.getName();
		value = Maps.getValueFromQualifiedName(row, propertyName);
		fvalue = WebEditors.format(request, p, value, errors, view.getViewName(), true);	
		Object title = WebEditors.formatTitle(request, p, value, errors, view.getViewName(), true); 

      out.write("\n");
      out.write("	<td class=\"");
      out.print(cssCellClass);
      out.write(' ');
      out.print(align);
      out.write(" ox-list-data-cell\">\n");
      out.write("	");
      //  xava:link
      org.openxava.web.taglib.LinkTag _jspx_th_xava_005flink_005f0 = (org.openxava.web.taglib.LinkTag) _005fjspx_005ftagPool_005fxava_005flink_0026_005fargv_005faction.get(org.openxava.web.taglib.LinkTag.class);
      boolean _jspx_th_xava_005flink_005f0_reused = false;
      try {
        _jspx_th_xava_005flink_005f0.setPageContext(_jspx_page_context);
        _jspx_th_xava_005flink_005f0.setParent(null);
        // /xava/editors/../collectionFromModel.jsp(131,1) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005flink_005f0.setAction(lineAction);
        // /xava/editors/../collectionFromModel.jsp(131,1) name = argv type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005flink_005f0.setArgv("row="+f + ",viewObject="+viewName);
        int _jspx_eval_xava_005flink_005f0 = _jspx_th_xava_005flink_005f0.doStartTag();
        if (_jspx_eval_xava_005flink_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	<div title=\"");
            out.print(title);
            out.write("\" class=\"");
            if (_jspx_meth_xava_005fid_005f5(_jspx_th_xava_005flink_005f0, _jspx_page_context))
              return;
            out.write(' ');
            //  xava:id
            org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f6 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
            boolean _jspx_th_xava_005fid_005f6_reused = false;
            try {
              _jspx_th_xava_005fid_005f6.setPageContext(_jspx_page_context);
              _jspx_th_xava_005fid_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_xava_005flink_005f0);
              // /xava/editors/../collectionFromModel.jsp(132,58) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_xava_005fid_005f6.setName(idCollection);
              int _jspx_eval_xava_005fid_005f6 = _jspx_th_xava_005fid_005f6.doStartTag();
              if (_jspx_th_xava_005fid_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f6);
              _jspx_th_xava_005fid_005f6_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f6, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f6_reused);
            }
            out.write("_col");
            out.print(columnIndex);
            out.write('"');
            out.write(' ');
            out.print(width);
            out.write('>');
            out.write('\n');
            out.write('	');
if (resizeColumns) {
            out.write("<nobr>");
}
            out.write('\n');
            out.write('	');
            out.print(fvalue);
            out.write("&nbsp; \n");
            out.write("	");
if (resizeColumns) {
            out.write("</nobr>");
}
            out.write("\n");
            out.write("	</div>\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_xava_005flink_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_xava_005flink_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005flink_0026_005fargv_005faction.reuse(_jspx_th_xava_005flink_005f0);
        _jspx_th_xava_005flink_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005flink_005f0, _jsp_getInstanceManager(), _jspx_th_xava_005flink_005f0_reused);
      }
      out.write("\n");
      out.write("	</td>\n");
      out.write("		\n");

	}
}

      out.write("\n");
      out.write("</tr>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "collectionTotals.jsp", out, false);
      out.write('\n');
 if (sortable) { 
      out.write("</tbody>");
 } 
      out.write("\n");
      out.write("</table>\n");
 if (resizeColumns) { 
      out.write("\n");
      out.write("</div>\n");
 } 
      out.write('\n');
      out.write(' ');
      out.write('\n');
      out.write('	');

		} else {
	
      out.write('\n');
      out.write('	');
      out.write('	');

String tabObject = org.openxava.web.Collections.tabObject(idCollection); 
org.openxava.tab.Tab tab = subview.getCollectionTab();

String tabPrefix = tabObject + "_";
tab.clearStyle();
int selectedRow = subview.getCollectionEditingRow();
if (selectedRow >= 0) {
	String cssClass=selectedRow%2==0?style.getListPairSelected():style.getListOddSelected();
	tab.setStyle(selectedRow, cssClass);
}
context.put(request, tabObject, tab);

// The list

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../list.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("collection", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(idCollection), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("rowAction", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(lineAction), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("tabObject", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(tabObject), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("viewObject", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(viewName), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("viewKeyEditable", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(view.isKeyEditable()), request.getCharacterEncoding()), out, false);
      out.write('\n');
      out.write('\n');
      out.write('	');

		}
	
      out.write('\n');

	} catch (Exception ex) {

      out.write("\n");
      out.write("</td></tr>\n");
      out.write("<tr><td class='ox-errors'>\n");
      out.print(ex.getLocalizedMessage());
      out.write('\n');

	}

      out.write("\n");
      out.write("</td></tr>\n");

	} // of: if (XavaPreferences...

      out.write('\n');

	// New
if (view.displayDetailInCollection(collectionName)) {
	context.put(request, viewName, collectionView);

      out.write("\n");
      out.write("<tr class=");
      out.print(style.getCollectionListActions());
      out.write("><td colspan=\"");
      out.print(subview.getMetaPropertiesList().size()+1);
      out.write("\" class=");
      out.print(style.getCollectionListActions());
      out.write('>');
      out.write('\n');

	if (collectionEditable) {

      out.write('\n');
 if (subview.isRepresentsEntityReference()) { 
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../barButton.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("action", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(subview.getAddCollectionElementAction()), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("argv", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf("viewObject="+viewName), request.getCharacterEncoding()), out, false);
      out.write('\n');
 } 
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../barButton.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("action", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(subview.getNewCollectionElementAction()), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("argv", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf("viewObject="+viewName), request.getCharacterEncoding()), out, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../barButton.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("action", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(subview.getRemoveSelectedCollectionElementsAction()), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("argv", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf("viewObject="+viewName), request.getCharacterEncoding()), out, false);
      out.write('\n');
      out.write('\n');

	}

      out.write('\n');

	Iterator itListActions = subview.getActionsNamesList().iterator();
while (itListActions.hasNext()) {

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../barButton.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("action", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(itListActions.next().toString()), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("argv", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf("viewObject="+viewName), request.getCharacterEncoding()), out, false);
      out.write('\n');

	} // while list actions
	
	Collection<String> listSubcontrollers = subview.getSubcontrollersNamesList();
	for(String listSubcontroller : listSubcontrollers){
		
      out.write('\n');
      out.write('	');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../subButton.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("controller", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(listSubcontroller), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("argv", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf("viewObject="+viewName), request.getCharacterEncoding()), out, false);
      out.write('\n');
      out.write('	');
      out.write('	');

	}

      out.write("\n");
      out.write("\n");
      out.write("</td></tr>\n");

	}
else {

      out.write("\n");
      out.write("<td></td>\n");

	String argv = "collectionName=" + collectionName;
	Iterator it = subview.getMetaPropertiesList().iterator();
	String app = request.getParameter("application");
	String module = request.getParameter("module");
	while (it.hasNext()) {
		MetaProperty p = (MetaProperty) it.next(); 
		String propertyKey= propertyPrefix + p.getName();
		String valueKey = propertyKey + ".value";
		request.setAttribute(propertyKey, p);
		request.setAttribute(valueKey, subview.getValue(p.getName()));
		Object value = request.getAttribute(propertyKey + ".value");
		if (WebEditors.mustToFormat(p, view.getViewName())) {
			String fvalue = WebEditors.format(request, p, value, errors, view.getViewName());
			request.setAttribute(propertyKey + ".fvalue", fvalue);
		}

      out.write("\n");
      out.write("	<td>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, WebEditors.getUrl(p, view.getViewName()) + ((WebEditors.getUrl(p, view.getViewName())).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("propertyKey", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(propertyKey), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("editable", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("true", request.getCharacterEncoding()), out, false);
      out.write("		\n");
      out.write("	</td>\n");
      out.write("	");

		}
	}
	
      out.write("\n");
      out.write("\n");
      out.write("</tr>\n");

	if (!XavaPreferences.getInstance().isDetailOnBottomInCollections()) {

      out.write("\n");
      out.write("<tr><td>\n");

	try {

      out.write('\n');
      out.write('	');

		if (!Is.emptyString(listEditor)) {
	
      out.write(" 		\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, listEditor + ((listEditor).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("rowAction", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(lineAction), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("viewObject", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(viewName), request.getCharacterEncoding()), out, false);
      out.write('\n');
      out.write('	');

		} else if (collectionView.isCollectionFromModel()) {
	
      out.write('\n');
      out.write('	');
      out.write('	');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

String tabObject = request.getParameter("tabObject"); 
tabObject = (tabObject == null || tabObject.equals(""))?"xava_tab":tabObject;
String onSelectCollectionElementAction = subview.getOnSelectCollectionElementAction();
MetaAction onSelectCollectionElementMetaAction = Is.empty(onSelectCollectionElementAction) ? null : MetaControllers.getMetaAction(onSelectCollectionElementAction);
boolean resizeColumns = style.allowsResizeColumns() && XavaPreferences.getInstance().isResizeColumns();
boolean sortable = subview.isCollectionSortable();

      out.write('\n');
 if (resizeColumns) { 
      out.write(" \n");
      out.write("<div class=\"");
      if (_jspx_meth_xava_005fid_005f7(_jspx_page_context))
        return;
      out.write(" ox-overflow-auto\">\n");
 } 
      out.write("\n");
      out.write("<table id=\"");
      //  xava:id
      org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f8 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
      boolean _jspx_th_xava_005fid_005f8_reused = false;
      try {
        _jspx_th_xava_005fid_005f8.setPageContext(_jspx_page_context);
        _jspx_th_xava_005fid_005f8.setParent(null);
        // /xava/editors/../collectionFromModel.jsp(20,11) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005fid_005f8.setName(idCollection);
        int _jspx_eval_xava_005fid_005f8 = _jspx_th_xava_005fid_005f8.doStartTag();
        if (_jspx_th_xava_005fid_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f8);
        _jspx_th_xava_005fid_005f8_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f8, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f8_reused);
      }
      out.write("\" class=\"ox-list\" ");
      out.print(style.getListCellSpacing());
      out.write('>');
      out.write('\n');
 if (sortable) { 
      out.write("<tbody class=\"xava_sortable_row\">");
 } 
      out.write(" \n");
      out.write("<tr class=\"ox-list-header\">\n");
      out.write("	");

		if (lineAction != null) {
	
      out.write("	\n");
      out.write("	<th class=\"ox-list-header\"></th>\n");
      out.write("	");

		}
	
      out.write("	\n");
      out.write("	<th class=\"ox-list-header\" width=\"5\">\n");
      out.write("	");

	
      out.write("\n");
      out.write("	<input type=\"checkbox\" name=\"");
      if (_jspx_meth_xava_005fid_005f9(_jspx_page_context))
        return;
      out.write("\" value=\"");
      out.print(propertyPrefix);
      out.write("selected_all\" \n");
      out.write("		data-on-select-collection-element-action=\"");
      out.print(onSelectCollectionElementAction);
      out.write("\"\n");
      out.write("		data-view-object=\"");
      out.print(idCollection);
      out.write("\"\n");
      out.write("		data-prefix=\"");
      out.print(propertyPrefix);
      out.write("\"\n");
      out.write("		data-tab-object=\"");
      out.print(tabObject);
      out.write("\"/>\n");
      out.write("	</th>\n");

	// Heading
Iterator it = subview.getMetaPropertiesList().iterator();
for (int columnIndex=0; it.hasNext(); columnIndex++) {
	MetaProperty p = (MetaProperty) it.next();
	String label = p.getQualifiedLabel(request);
	int columnWidth = subview.getCollectionColumnWidth(columnIndex);
	String width = columnWidth<0 || !resizeColumns?"":"data-width=" + columnWidth;

      out.write("\n");
      out.write("	<th class=\"ox-list-header ox-padding-right-0\">\n");
      out.write("		<div id=\"");
      //  xava:id
      org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f10 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
      boolean _jspx_th_xava_005fid_005f10_reused = false;
      try {
        _jspx_th_xava_005fid_005f10.setPageContext(_jspx_page_context);
        _jspx_th_xava_005fid_005f10.setParent(null);
        // /xava/editors/../collectionFromModel.jsp(49,11) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005fid_005f10.setName(idCollection);
        int _jspx_eval_xava_005fid_005f10 = _jspx_th_xava_005fid_005f10.doStartTag();
        if (_jspx_th_xava_005fid_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f10);
        _jspx_th_xava_005fid_005f10_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f10, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f10_reused);
      }
      out.write("_col");
      out.print(columnIndex);
      out.write("\" class=\"");
      out.print(((resizeColumns)?("xava_resizable"):("")));
      out.write('"');
      out.write(' ');
      out.print(width);
      out.write(">\n");
      out.write("		");
if (resizeColumns) {
      out.write("<nobr>");
}
      out.write('\n');
      out.write('	');
      out.write('	');
      out.print(label);
      out.write("&nbsp;\n");
      out.write("		");
if (resizeColumns) {
      out.write("</nobr>");
}
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</th>\n");

	}

      out.write("\n");
      out.write("</tr>\n");
      out.write("\n");

	// Values
Collection aggregates = subview.getCollectionValues();
View parent = view.getParent();
boolean parentHasSections = parent != null && parent.hasSections();
boolean condition = (view.isKeyEditable() && parentHasSections && !view.isRepresentsEntityReference()); 
if (aggregates == null || condition) aggregates = java.util.Collections.EMPTY_LIST;
Iterator itAggregates = aggregates.iterator();
for (int f=0; itAggregates.hasNext(); f++) {
	Map row = (Map) itAggregates.next();
	String cssClass=f%2==0?"ox-list-pair":"ox-list-odd";
	String cssCellClass=f%2==0?"ox-list-pair":"ox-list-odd";
	String selectedClass = "";
	if (f == subview.getCollectionEditingRow()) { 
		selectedClass = f%2==0?style.getListPairSelected():style.getListOddSelected();
		cssClass = cssClass + " " + selectedClass;		
		if (style.isApplySelectedStyleToCellInList()) cssCellClass = cssCellClass + " " + selectedClass; 
	}		
	String idRow = Ids.decorate(request, propertyPrefix) + f;	
	String events=f%2==0?style.getListPairEvents():style.getListOddEvents(); 

      out.write("\n");
      out.write("<tr id=\"");
      out.print(idRow);
      out.write("\" class=\"");
      out.print(cssClass);
      out.write('"');
      out.write(' ');
      out.print(events);
      out.write('>');
      out.write('\n');

	if (lineAction != null) {

      out.write("\n");
      out.write("<td class=\"");
      out.print(cssCellClass);
      out.write(" ox-list-action-cell\">\n");
      out.write("<nobr>\n");
      out.write("	");
	if (sortable) { 
      out.write("\n");
      out.write("	<i class=\"xava_handle mdi mdi-swap-vertical\"></i>	\n");
      out.write("	");
  } 
      out.write('	');
      out.write('\n');
      //  xava:action
      org.openxava.web.taglib.ActionTag _jspx_th_xava_005faction_005f2 = (org.openxava.web.taglib.ActionTag) _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.get(org.openxava.web.taglib.ActionTag.class);
      boolean _jspx_th_xava_005faction_005f2_reused = false;
      try {
        _jspx_th_xava_005faction_005f2.setPageContext(_jspx_page_context);
        _jspx_th_xava_005faction_005f2.setParent(null);
        // /xava/editors/../collectionFromModel.jsp(90,0) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005faction_005f2.setAction(lineAction);
        // /xava/editors/../collectionFromModel.jsp(90,0) name = argv type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005faction_005f2.setArgv("row="+f + ",viewObject="+viewName);
        int _jspx_eval_xava_005faction_005f2 = _jspx_th_xava_005faction_005f2.doStartTag();
        if (_jspx_th_xava_005faction_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.reuse(_jspx_th_xava_005faction_005f2);
        _jspx_th_xava_005faction_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005faction_005f2, _jsp_getInstanceManager(), _jspx_th_xava_005faction_005f2_reused);
      }
      out.write('\n');
 
		if (style.isSeveralActionsPerRow())
			for (java.util.Iterator itRowActions = subview.getRowActionsNames().iterator(); itRowActions.hasNext(); ) { 	
				String rowAction = (String) itRowActions.next();		

      out.write('\n');
      //  xava:action
      org.openxava.web.taglib.ActionTag _jspx_th_xava_005faction_005f3 = (org.openxava.web.taglib.ActionTag) _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.get(org.openxava.web.taglib.ActionTag.class);
      boolean _jspx_th_xava_005faction_005f3_reused = false;
      try {
        _jspx_th_xava_005faction_005f3.setPageContext(_jspx_page_context);
        _jspx_th_xava_005faction_005f3.setParent(null);
        // /xava/editors/../collectionFromModel.jsp(96,0) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005faction_005f3.setAction(rowAction);
        // /xava/editors/../collectionFromModel.jsp(96,0) name = argv type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005faction_005f3.setArgv("row=" + f + ",viewObject="+viewName);
        int _jspx_eval_xava_005faction_005f3 = _jspx_th_xava_005faction_005f3.doStartTag();
        if (_jspx_th_xava_005faction_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.reuse(_jspx_th_xava_005faction_005f3);
        _jspx_th_xava_005faction_005f3_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005faction_005f3, _jsp_getInstanceManager(), _jspx_th_xava_005faction_005f3_reused);
      }
      out.write('\n');

		}

      out.write("\n");
      out.write("</nobr>\n");
      out.write("</td>\n");

	} 

      out.write("\n");
      out.write("<td class=\"");
      out.print(cssCellClass);
      out.write("\" width=\"5\">\n");
      out.write("<input class=\"xava_selected\" type=\"checkbox\" name=\"");
      if (_jspx_meth_xava_005fid_005f11(_jspx_page_context))
        return;
      out.write("\" value=\"");
      out.print(propertyPrefix);
      out.write("__SELECTED__:");
      out.print(f);
      out.write("\" \n");
      out.write("	data-on-select-collection-element-action=\"");
      out.print(onSelectCollectionElementAction);
      out.write("\"\n");
      out.write("	data-row-id=\"");
      out.print(idRow);
      out.write("\"\n");
      out.write("	data-row=\"");
      out.print(f);
      out.write("\"\n");
      out.write("	data-view-object=\"");
      out.print(viewName);
      out.write("\"\n");
      out.write("	data-tab-object=\"");
      out.print(tabObject);
      out.write("\"\n");
      out.write("	data-confirm-message=\"");
      out.print(Is.empty(onSelectCollectionElementMetaAction)?"":onSelectCollectionElementMetaAction.getConfirmMessage());
      out.write("\"\n");
      out.write("	data-takes-long=\"");
      out.print(Is.empty(onSelectCollectionElementMetaAction)?false:onSelectCollectionElementMetaAction.isTakesLong());
      out.write("\"\n");
      out.write("/>\n");
      out.write("</td>\n");

	it = subview.getMetaPropertiesList().iterator();	
	for (int columnIndex = 0; it.hasNext(); columnIndex++) { 
		MetaProperty p = (MetaProperty) it.next();
		String align =p.isNumber() && !p.hasValidValues()?"ox-text-align-right":"";
		int columnWidth = subview.getCollectionColumnWidth(columnIndex);
		String width = columnWidth<0 || !resizeColumns?"":"data-width=" + columnWidth; 
		String fvalue = null;
		Object value = null;
		String propertyName = p.getName();
		value = Maps.getValueFromQualifiedName(row, propertyName);
		fvalue = WebEditors.format(request, p, value, errors, view.getViewName(), true);	
		Object title = WebEditors.formatTitle(request, p, value, errors, view.getViewName(), true); 

      out.write("\n");
      out.write("	<td class=\"");
      out.print(cssCellClass);
      out.write(' ');
      out.print(align);
      out.write(" ox-list-data-cell\">\n");
      out.write("	");
      //  xava:link
      org.openxava.web.taglib.LinkTag _jspx_th_xava_005flink_005f1 = (org.openxava.web.taglib.LinkTag) _005fjspx_005ftagPool_005fxava_005flink_0026_005fargv_005faction.get(org.openxava.web.taglib.LinkTag.class);
      boolean _jspx_th_xava_005flink_005f1_reused = false;
      try {
        _jspx_th_xava_005flink_005f1.setPageContext(_jspx_page_context);
        _jspx_th_xava_005flink_005f1.setParent(null);
        // /xava/editors/../collectionFromModel.jsp(131,1) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005flink_005f1.setAction(lineAction);
        // /xava/editors/../collectionFromModel.jsp(131,1) name = argv type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_xava_005flink_005f1.setArgv("row="+f + ",viewObject="+viewName);
        int _jspx_eval_xava_005flink_005f1 = _jspx_th_xava_005flink_005f1.doStartTag();
        if (_jspx_eval_xava_005flink_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	<div title=\"");
            out.print(title);
            out.write("\" class=\"");
            if (_jspx_meth_xava_005fid_005f12(_jspx_th_xava_005flink_005f1, _jspx_page_context))
              return;
            out.write(' ');
            //  xava:id
            org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f13 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
            boolean _jspx_th_xava_005fid_005f13_reused = false;
            try {
              _jspx_th_xava_005fid_005f13.setPageContext(_jspx_page_context);
              _jspx_th_xava_005fid_005f13.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_xava_005flink_005f1);
              // /xava/editors/../collectionFromModel.jsp(132,58) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_xava_005fid_005f13.setName(idCollection);
              int _jspx_eval_xava_005fid_005f13 = _jspx_th_xava_005fid_005f13.doStartTag();
              if (_jspx_th_xava_005fid_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f13);
              _jspx_th_xava_005fid_005f13_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f13, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f13_reused);
            }
            out.write("_col");
            out.print(columnIndex);
            out.write('"');
            out.write(' ');
            out.print(width);
            out.write('>');
            out.write('\n');
            out.write('	');
if (resizeColumns) {
            out.write("<nobr>");
}
            out.write('\n');
            out.write('	');
            out.print(fvalue);
            out.write("&nbsp; \n");
            out.write("	");
if (resizeColumns) {
            out.write("</nobr>");
}
            out.write("\n");
            out.write("	</div>\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_xava_005flink_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_xava_005flink_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005flink_0026_005fargv_005faction.reuse(_jspx_th_xava_005flink_005f1);
        _jspx_th_xava_005flink_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005flink_005f1, _jsp_getInstanceManager(), _jspx_th_xava_005flink_005f1_reused);
      }
      out.write("\n");
      out.write("	</td>\n");
      out.write("		\n");

	}
}

      out.write("\n");
      out.write("</tr>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "collectionTotals.jsp", out, false);
      out.write('\n');
 if (sortable) { 
      out.write("</tbody>");
 } 
      out.write("\n");
      out.write("</table>\n");
 if (resizeColumns) { 
      out.write("\n");
      out.write("</div>\n");
 } 
      out.write('\n');
      out.write(' ');
      out.write('\n');
      out.write('	');
 } else { 
      out.write('\n');
      out.write('	');
      out.write('	');

String tabObject = org.openxava.web.Collections.tabObject(idCollection); 
org.openxava.tab.Tab tab = subview.getCollectionTab();

String tabPrefix = tabObject + "_";
tab.clearStyle();
int selectedRow = subview.getCollectionEditingRow();
if (selectedRow >= 0) {
	String cssClass=selectedRow%2==0?style.getListPairSelected():style.getListOddSelected();
	tab.setStyle(selectedRow, cssClass);
}
context.put(request, tabObject, tab);

// The list

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../list.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("collection", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(idCollection), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("rowAction", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(lineAction), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("tabObject", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(tabObject), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("viewObject", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(viewName), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("viewKeyEditable", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(view.isKeyEditable()), request.getCharacterEncoding()), out, false);
      out.write('\n');
      out.write('\n');
      out.write('	');
 } 
      out.write('\n');
 } catch (Exception ex) { 
      out.write("\n");
      out.write("</td></tr>\n");
      out.write("<tr><td class='ox-errors'>\n");
      out.print(ex.getLocalizedMessage());
      out.write('\n');
 } 
      out.write("\n");
      out.write("</td></tr>\n");
 } // of: if (!XavaPreferences... 
      out.write("\n");
      out.write("</table>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_xava_005fid_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f0 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    boolean _jspx_th_xava_005fid_005f0_reused = false;
    try {
      _jspx_th_xava_005fid_005f0.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fid_005f0.setParent(null);
      // /xava/editors/../collectionFromModel.jsp(18,12) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005fid_005f0.setName("collection_scroll");
      int _jspx_eval_xava_005fid_005f0 = _jspx_th_xava_005fid_005f0.doStartTag();
      if (_jspx_th_xava_005fid_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f0);
      _jspx_th_xava_005fid_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f0, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_xava_005fid_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f2 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    boolean _jspx_th_xava_005fid_005f2_reused = false;
    try {
      _jspx_th_xava_005fid_005f2.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fid_005f2.setParent(null);
      // /xava/editors/../collectionFromModel.jsp(33,30) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005fid_005f2.setName("xava_selected_all");
      int _jspx_eval_xava_005fid_005f2 = _jspx_th_xava_005fid_005f2.doStartTag();
      if (_jspx_th_xava_005fid_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f2);
      _jspx_th_xava_005fid_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f2, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_xava_005fid_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f4 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    boolean _jspx_th_xava_005fid_005f4_reused = false;
    try {
      _jspx_th_xava_005fid_005f4.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fid_005f4.setParent(null);
      // /xava/editors/../collectionFromModel.jsp(106,51) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005fid_005f4.setName("xava_selected");
      int _jspx_eval_xava_005fid_005f4 = _jspx_th_xava_005fid_005f4.doStartTag();
      if (_jspx_th_xava_005fid_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f4);
      _jspx_th_xava_005fid_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f4, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_xava_005fid_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_xava_005flink_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f5 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    boolean _jspx_th_xava_005fid_005f5_reused = false;
    try {
      _jspx_th_xava_005fid_005f5.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fid_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_xava_005flink_005f0);
      // /xava/editors/../collectionFromModel.jsp(132,32) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005fid_005f5.setName("tipable");
      int _jspx_eval_xava_005fid_005f5 = _jspx_th_xava_005fid_005f5.doStartTag();
      if (_jspx_th_xava_005fid_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f5);
      _jspx_th_xava_005fid_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f5, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_xava_005fid_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f7 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    boolean _jspx_th_xava_005fid_005f7_reused = false;
    try {
      _jspx_th_xava_005fid_005f7.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fid_005f7.setParent(null);
      // /xava/editors/../collectionFromModel.jsp(18,12) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005fid_005f7.setName("collection_scroll");
      int _jspx_eval_xava_005fid_005f7 = _jspx_th_xava_005fid_005f7.doStartTag();
      if (_jspx_th_xava_005fid_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f7);
      _jspx_th_xava_005fid_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f7, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_xava_005fid_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f9 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    boolean _jspx_th_xava_005fid_005f9_reused = false;
    try {
      _jspx_th_xava_005fid_005f9.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fid_005f9.setParent(null);
      // /xava/editors/../collectionFromModel.jsp(33,30) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005fid_005f9.setName("xava_selected_all");
      int _jspx_eval_xava_005fid_005f9 = _jspx_th_xava_005fid_005f9.doStartTag();
      if (_jspx_th_xava_005fid_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f9);
      _jspx_th_xava_005fid_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f9, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_xava_005fid_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f11 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    boolean _jspx_th_xava_005fid_005f11_reused = false;
    try {
      _jspx_th_xava_005fid_005f11.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fid_005f11.setParent(null);
      // /xava/editors/../collectionFromModel.jsp(106,51) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005fid_005f11.setName("xava_selected");
      int _jspx_eval_xava_005fid_005f11 = _jspx_th_xava_005fid_005f11.doStartTag();
      if (_jspx_th_xava_005fid_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f11);
      _jspx_th_xava_005fid_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f11, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_xava_005fid_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_xava_005flink_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f12 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    boolean _jspx_th_xava_005fid_005f12_reused = false;
    try {
      _jspx_th_xava_005fid_005f12.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fid_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_xava_005flink_005f1);
      // /xava/editors/../collectionFromModel.jsp(132,32) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005fid_005f12.setName("tipable");
      int _jspx_eval_xava_005fid_005f12 = _jspx_th_xava_005fid_005f12.doStartTag();
      if (_jspx_th_xava_005fid_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f12);
      _jspx_th_xava_005fid_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f12, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f12_reused);
    }
    return false;
  }
}
